FROM node:20-alpine AS base
RUN corepack enable pnpm

FROM base AS deps
WORKDIR /app
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* ./
COPY packages/ ./packages/
COPY apps/ ./apps/
COPY services/ ./services/
RUN pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app
COPY --from=deps /app ./
COPY . .
ARG SERVICE_PATH
RUN pnpm --filter @mifos-x/shared-types build
RUN pnpm --filter "./${SERVICE_PATH}" build
RUN pnpm deploy --filter "./${SERVICE_PATH}" --prod /deploy

FROM base AS runner
WORKDIR /app
COPY --from=builder /deploy ./
CMD ["node", "dist/index.js"]
